name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt -q update
        apt -q -y install kmod qemu-kvm
        kvm-ok
